# Generated by Django 5.1.1 on 2024-10-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_is_verified_otpmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
