# Generated by Django 5.1.1 on 2024-12-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_changerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='target_table_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
