# Generated by Django 5.1.1 on 2024-12-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_alter_changerequest_target_table_id'),
        ('project_manager', '0008_alter_issue_assignee_alter_issue_reporter_and_more'),
    ]

    operations = [
    ]
