# Generated by Django 5.1.1 on 2024-12-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0009_merge_20241206_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='actual_start_date',
        ),
    ]
