# Generated by Django 5.1.1 on 2024-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='object',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
