# Generated by Django 5.1.1 on 2024-12-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationlog_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
