# Generated by Django 5.1.1 on 2025-01-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('MEMBER_ADD', 'Member Add'), ('MEMBER_REMOVE', 'Member Remove'), ('TASK_ADD', 'Task Add'), ('TASK_UPDATE', 'Task Update'), ('TASK_REMOVE', 'Task Remove'), ('COMMENT_ADD', 'Comment Add'), ('COMMENT_UPDATE', 'Comment Update'), ('COMMENT_REMOVE', 'Comment Remove'), ('ISSUE_ADD', 'Issue Add'), ('ISSUE_UPDATE', 'Issue Update'), ('ISSUE_REMOVE', 'Issue Remove'), ('ROLE_ADD', 'Role Add'), ('ROLE_UPDATE', 'Role Update'), ('ROLE_REMOVE', 'Role Remove'), ('ROLE_ASSIGN', 'Role Assign'), ('ROLE_UNASSIGN', 'Role Unassign')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project_manager.project')),
            ],
        ),
    ]
