# Generated by Django 5.1.1 on 2024-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('MEMBER_ADD', 'Member Add'), ('MEMBER_REMOVE', 'Member Remove'), ('TASK_ADD', 'Task Add'), ('TASK_UPDATE', 'Task Update'), ('TASK_REMOVE', 'Task Remove')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
