# Generated by Django 5.1.1 on 2024-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_alter_activitylog_options_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('MEMBER_ADD', 'Member Add'), ('MEMBER_REMOVE', 'Member Remove'), ('TASK_ADD', 'Task Add'), ('TASK_UPDATE', 'Task Update'), ('TASK_REMOVE', 'Task Remove'), ('COMMENT_ADD', 'Comment Add'), ('COMMENT_UPDATE', 'Comment Update'), ('COMMENT_REMOVE', 'Comment Remove')], max_length=20),
        ),
    ]
