# Generated by Django 5.1.1 on 2024-12-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('MEMBER_ADD', 'Member Add'), ('MEMBER_REMOVE', 'Member Remove'), ('TASK_ADD', 'Task Add'), ('TASK_UPDATE', 'Task Update'), ('TASK_REMOVE', 'Task Remove'), ('COMMENT_ADD', 'Comment Add'), ('COMMENT_UPDATE', 'Comment Update'), ('COMMENT_REMOVE', 'Comment Remove'), ('ISSUE_ADD', 'Issue Add'), ('ISSUE_UPDATE', 'Issue Update'), ('ISSUE_REMOVE', 'Issue Remove'), ('ROLE_ADD', 'Role Add'), ('ROLE_UPDATE', 'Role Update'), ('ROLE_REMOVE', 'Role Remove'), ('ROLE_ASSIGN', 'Role Assign'), ('ROLE_UNASSIGN', 'Role Unassign')], max_length=20),
        ),
    ]
